### ISSUE TITLE
升级到pixi.js 7.4.0 vue3-pixi 0.9.1后，报错：ReferenceError: Worker is not defined

### ISSUE THREAD

**Issue by xeoshow** [hairyf/vue3-pixi-dino#2]
你好，我在尝试搭建本demo项目，直接运行没问题，但看到pixi.js和vue3-pixi有更新的版本了，升级到pixi.js 7.4.0 vue3-pixi 0.9.1后，有如下报错：
```
D:\gitrepository\vue3-pixi-dino-main>pnpm i
Packages: +119
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 154, reused 119, downloaded 0, added 119, done
node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild: Running postinstall script, done in 186ms

dependencies:
+ @vueuse/core 10.9.0
+ pixi.js 7.4.0
+ ts-audio 0.7.4
+ vue 3.4.21
+ vue3-pixi 0.9.1

devDependencies:
+ @vitejs/plugin-vue 5.0.4
+ typescript 5.3.3
+ vite 5.1.4
+ vue-tsc 2.0.4

Done in 2.2s

D:\gitrepository\vue3-pixi-dino-main>pnpm run dev

> my-vue-app@0.0.0 dev D:\gitrepository\vue3-pixi-dino-main
> vite

failed to load config from D:\gitrepository\vue3-pixi-dino-main\vite.config.ts
error when starting dev server:
ReferenceError: Worker is not defined
    at file:///D:/gitrepository/vue3-pixi-dino-main/node_modules/.pnpm/@pixi+assets@7.4.0_@pixi+core@7.4.0/node_modules/@pixi/assets/lib/_virtual/checkImageBitmap.worker.mjs:20:30
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadConfigFromBundledFile (file:///D:/gitrepository/vue3-pixi-dino-main/node_modules/.pnpm/vite@5.1.4/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:68152:21)
    at async loadConfigFromFile (file:///D:/gitrepository/vue3-pixi-dino-main/node_modules/.pnpm/vite@5.1.4/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:68007:28)
    at async resolveConfig (file:///D:/gitrepository/vue3-pixi-dino-main/node_modules/.pnpm/vite@5.1.4/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67619:28)
    at async _createServer (file:///D:/gitrepository/vue3-pixi-dino-main/node_modules/.pnpm/vite@5.1.4/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:64257:20)
    at async CAC.<anonymous> (file:///D:/gitrepository/vue3-pixi-dino-main/node_modules/.pnpm/vite@5.1.4/node_modules/vite/dist/node/cli.js:762:24)
 ELIFECYCLE  Command failed with exit code 1.

D:\gitrepository\vue3-pixi-dino-main>
```

**Comment by xeoshow** [comment]
现在的package.json:
```
{
  "name": "my-vue-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@vueuse/core": "10.9.0",
    "pixi.js": "7.4.0",
    "ts-audio": "0.7.4",
    "vue": "3.4.21",
    "vue3-pixi": "0.9.1"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "typescript": "^5.3.3",
    "vite": "^5.1.4",
    "vue-tsc": "^2.0.4"
  }
}
```
